[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
im = "15.1.0"
k9 = "0.12.0"
rand = "0.8.5"
rayon = "1.8.1"
